const people=
[
    {
        "id":1,
        "name":"Chaya",
        "mark":12,
        "desc":"sweet"
    },
    {
        "id":2,
        "name":"Nechama",
        "mark":50,
        "desc":"amazing"
    },
    {
        "id":3,
        "name":"Moshe",
        "mark":75,
        "desc":"lovely"
    },
    {
        "id":4,
        "name":"Varda",
        "mark":98,
        "desc":"smart"
    },
    {
        "id":5,
        "name":"Miri",
        "mark":78,
        "desc":"nice"
    },
    {
        "id":6,
        "name":"Shoshana",
        "mark":45,
        "desc":"Tall"
    },
    {
        "id":7,
        "name":"Avi",
        "mark":100,
        "desc":"Fat"
    },
    {
        "id":8,
        "name":"Cobi",
        "mark":68,
        "desc":"wonderfall"
    }
]
module.exports={people}